name: NetVideo Series

on:
  schedule:
    - cron: '0 14 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # --- AQUÍ ESTÁ LA SOLUCIÓN AL ERROR 403 ---
    permissions:
      contents: write
    # ------------------------------------------

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - run: pip install requests

      - name: Generar Series NetVideo
        env:
          URL_SERVIDOR: ${{ secrets.URL_SERVIDOR }} 
        run: python netvideo_series.py

      - name: Guardar
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot Series"
          git add netvideo.series.m3u
          git commit -m "Update Series NV" || echo "Sin cambios"
          git push
