name: NetVideo Pelis (Python)

on:
  schedule:
    # Ejecutar cada 6 horas (00:00, 06:00, 12:00, 18:00 UTC)
    # Esto equivale a las 6:00 PM, 12:00 AM, 6:00 AM y 12:00 PM de MÃ©xico
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Instalar Dependencias
      run: pip install requests
      
    - name: Ejecutar Script Peliculas
      env:
        URL_SERVIDOR: ${{ secrets.URL_SERVIDOR }}
      run: python netvideo.py
      
    - name: Subir a Gist (Python Directo)
      env:
        GH_TOKEN: ${{ secrets.TOKEN_GIST }}
        GIST_ID_PELIS: ${{ secrets.GIST_ID_PELIS }}
      run: python subir_netvideo.py

