name: Actualizar NetVideo Pelis (Python)

on:
  # 1. Horario Automático: Cada 6 horas
  # (00:00, 06:00, 12:00, 18:00 UTC)
  schedule:
    - cron: '0 */6 * * *'

  # 2. Botón Manual
  workflow_dispatch:

  # 3. Activador al Guardar (Solo afectará a este archivo)
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Instalar Dependencias
      run: pip install requests
      
    - name: Ejecutar Script Peliculas
      env:
        URL_SERVIDOR: ${{ secrets.URL_SERVIDOR }}
      run: python netvideo.py
      
    - name: Subir a Gist (Python Directo)
      env:
        GH_TOKEN: ${{ secrets.TOKEN_GIST }}
        GIST_ID_PELIS: ${{ secrets.GIST_ID_PELIS }}
      run: python subir_netvideo.py
