name: NetVideo Series

on:
  schedule:
    # CRON ACTUALIZADO: Ejecutar cada 6 horas (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # PERMISO DE ESCRITURA (CRUCIAL)
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - run: pip install requests

      - name: Generar Series NetVideo
        env:
          URL_SERVIDOR: ${{ secrets.URL_SERVIDOR }} 
        run: python netvideo_series.py

      - name: Guardar
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot Series"
          # Hacemos un pull antes por si el otro bot actualizó algo mientras tanto
          git pull origin main --rebase || echo "Repo al día"
          
          git add netvideo.series.m3u
          git commit -m "Update Series NV (Refresh Tokens)" || echo "Sin cambios"
          git push
